export enum Interaction {
    AMOUNT_SELECTED = 'AMOUNT_SELECTED',
    AMOUNT_SELECTED_CUSTOM = 'AMOUNT_SELECTED_CUSTOM',
    BANKRUPTCY_DECLARED = 'BANKRUPTCY_DECLARED',
    BANKRUPTCY_DENIED = 'BANKRUPTCY_DENIED',
    BET_LOSE = 'BET_LOSE',
    BET_WIN = 'BET_WIN',
}
